server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: video-service
          uri: http://localhost:8082
          predicates:
            - Path=/videos/**
        - id: recommendation-service
          uri: http://localhost:8083
          predicates:
            - Path=/recommendations/**
        - id: analytics-service
          uri: http://localhost:8084
          predicates:
            - Path=/analytics/**
        - id: transcoding-service
          uri: http://localhost:8085
          predicates:
            - Path=/transcoding/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

logging:
  level:
    org.springframework: INFO
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true