server:
  port: 8081
  servlet:
    context-path: /video

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/videoservice_db
    username: video_user
    password: securepassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.website.videoservice: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000