# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the build output from the current directory to the container
COPY ./build/libs/user-service.jar /app/user-service.jar

# Expose the port the service will run on
EXPOSE 8080

# Define the command to run the application
ENTRYPOINT ["java", "-jar", "/app/user-service.jar"]